### ISSUE TITLE
大佬可以联系 一下你吗?我搭建完成了.但是不知道主页怎么进

### ISSUE THREAD

**Issue by q2333gh** [by-night/sms#18]
jar包编译运行好了.但是在浏览器不知道怎么访问.打开http://localhost:8443/ 显示Whitelabel Error Page.
是不是哪个地方出了问题啊?

**Comment by Zjh-project** [comment]
> jar包编译运行好了.但是在浏览器不知道怎么访问.打开http://localhost:8443/ 显示Whitelabel Error Page.
> 是不是哪个地方出了问题啊?

前端没打包，所以你得先把前端启动一下

**Comment by Zjh-project** [comment]
> jar包编译运行好了.但是在浏览器不知道怎么访问.打开http://localhost:8443/ 显示Whitelabel Error Page.
> 是不是哪个地方出了问题啊?

你重新拉一下，应该可以了

**Comment by q2333gh** [comment]
大佬可以加一下你的qq吗，有几个小需求有偿请你加一下可以吗

**Comment by q2333gh** [comment]
大佬可以加一下你的qq吗，有几个小需求有偿请你加一下可以吗

**Comment by q2333gh** [comment]
我的qq是1253102853

**Comment by Zjh-project** [comment]
> 我的qq是1253102853

好的，加你了

**Comment by wangtingx** [comment]
数据库连接了，但是一直账号密码错误，大佬可以帮忙看看吗？我qq2982737978

**Comment by yangboperfect** [comment]
大佬，我QQ：2794401449   项目运行完毕了没问题，想问你一下运行原理流程和一些网页参数咋修改
