### ISSUE TITLE
大佬想请问一下，教师列表显示错误，想改网页发现网页端不是html，请问怎么修改好

### ISSUE THREAD

**Issue by Wodozpen** [by-night/sms#27]

**Comment by by-night** [comment]
报的什么错误

**Comment by Wodozpen** [comment]
报 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'student_mis.a.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
大佬我的QQ是3067774775可以方便加QQ吗

**Comment by by-night** [comment]
> 报 SELECT 列表的表达式#1不在 GROUP BY 子句中，并且包含非聚合列“student_mis.a.id”，它在功能上不依赖于 GROUP BY 子句中的列；这个不兼容sql_mode=only_full_group_by 大佬我的QQ是3067774775可以方便加QQ吗
加你了

**Comment by WY191** [comment]
大佬，你解决这个问题了吗
